//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.04 at 04:37:34 PM CEST 
//


package pl.bsb.b2b.h2o.helper;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.bsb.b2b.h2o.helper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CpaId_QNAME = new QName("", "cpaId");
    private final static QName _MaximumRetries_QNAME = new QName("", "maximumRetries");
    private final static QName _CertificateForEncryption_QNAME = new QName("", "certificateForEncryption");
    private final static QName _AcknowledgementRequested_QNAME = new QName("", "acknowledgementRequested");
    private final static QName _TransportEndpoint_QNAME = new QName("", "transportEndpoint");
    private final static QName _SigningRequired_QNAME = new QName("", "signingRequired");
    private final static QName _ReceiverWSURL_QNAME = new QName("", "receiverWSURL");
    private final static QName _ToPartyType_QNAME = new QName("", "toPartyType");
    private final static QName _SenderWSURL_QNAME = new QName("", "senderWSURL");
    private final static QName _NumOfMessages_QNAME = new QName("", "numOfMessages");
    private final static QName _FromPartyId_QNAME = new QName("", "fromPartyId");
    private final static QName _HostnameVerfiedInSsl_QNAME = new QName("", "hostnameVerfiedInSsl");
    private final static QName _CertificateForVerification_QNAME = new QName("", "certificateForVerification");
    private final static QName _AcknowledgementSignedRequest_QNAME = new QName("", "acknowledgementSignedRequest");
    private final static QName _MessageOrder_QNAME = new QName("", "messageOrder");
    private final static QName _Action_QNAME = new QName("", "action");
    private final static QName _Service_QNAME = new QName("", "service");
    private final static QName _ReceiverListWSURL_QNAME = new QName("", "receiverListWSURL");
    private final static QName _DuplicateElimination_QNAME = new QName("", "duplicateElimination");
    private final static QName _FromPartyType_QNAME = new QName("", "fromPartyType");
    private final static QName _EncryptionRequired_QNAME = new QName("", "encryptionRequired");
    private final static QName _SyncReplyMode_QNAME = new QName("", "syncReplyMode");
    private final static QName _ToPartyId_QNAME = new QName("", "toPartyId");
    private final static QName _RetryInterval_QNAME = new QName("", "retryInterval");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.bsb.b2b.h2o.helper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cpaId")
    public JAXBElement<String> createCpaId(String value) {
        return new JAXBElement<String>(_CpaId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maximumRetries")
    public JAXBElement<Integer> createMaximumRetries(Integer value) {
        return new JAXBElement<Integer>(_MaximumRetries_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "certificateForEncryption")
    public JAXBElement<String> createCertificateForEncryption(String value) {
        return new JAXBElement<String>(_CertificateForEncryption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acknowledgementRequested")
    public JAXBElement<Boolean> createAcknowledgementRequested(Boolean value) {
        return new JAXBElement<Boolean>(_AcknowledgementRequested_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transportEndpoint")
    public JAXBElement<String> createTransportEndpoint(String value) {
        return new JAXBElement<String>(_TransportEndpoint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "signingRequired")
    public JAXBElement<Boolean> createSigningRequired(Boolean value) {
        return new JAXBElement<Boolean>(_SigningRequired_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "receiverWSURL")
    public JAXBElement<String> createReceiverWSURL(String value) {
        return new JAXBElement<String>(_ReceiverWSURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "toPartyType")
    public JAXBElement<String> createToPartyType(String value) {
        return new JAXBElement<String>(_ToPartyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "senderWSURL")
    public JAXBElement<String> createSenderWSURL(String value) {
        return new JAXBElement<String>(_SenderWSURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numOfMessages")
    public JAXBElement<Integer> createNumOfMessages(Integer value) {
        return new JAXBElement<Integer>(_NumOfMessages_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fromPartyId")
    public JAXBElement<String> createFromPartyId(String value) {
        return new JAXBElement<String>(_FromPartyId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostnameVerfiedInSsl")
    public JAXBElement<Boolean> createHostnameVerfiedInSsl(Boolean value) {
        return new JAXBElement<Boolean>(_HostnameVerfiedInSsl_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "certificateForVerification")
    public JAXBElement<String> createCertificateForVerification(String value) {
        return new JAXBElement<String>(_CertificateForVerification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acknowledgementSignedRequest")
    public JAXBElement<Boolean> createAcknowledgementSignedRequest(Boolean value) {
        return new JAXBElement<Boolean>(_AcknowledgementSignedRequest_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "messageOrder")
    public JAXBElement<Boolean> createMessageOrder(Boolean value) {
        return new JAXBElement<Boolean>(_MessageOrder_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action")
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "service")
    public JAXBElement<String> createService(String value) {
        return new JAXBElement<String>(_Service_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "receiverListWSURL")
    public JAXBElement<String> createReceiverListWSURL(String value) {
        return new JAXBElement<String>(_ReceiverListWSURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "duplicateElimination")
    public JAXBElement<Boolean> createDuplicateElimination(Boolean value) {
        return new JAXBElement<Boolean>(_DuplicateElimination_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fromPartyType")
    public JAXBElement<String> createFromPartyType(String value) {
        return new JAXBElement<String>(_FromPartyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "encryptionRequired")
    public JAXBElement<Boolean> createEncryptionRequired(Boolean value) {
        return new JAXBElement<Boolean>(_EncryptionRequired_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "syncReplyMode")
    public JAXBElement<Boolean> createSyncReplyMode(Boolean value) {
        return new JAXBElement<Boolean>(_SyncReplyMode_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "toPartyId")
    public JAXBElement<String> createToPartyId(String value) {
        return new JAXBElement<String>(_ToPartyId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "retryInterval")
    public JAXBElement<Integer> createRetryInterval(Integer value) {
        return new JAXBElement<Integer>(_RetryInterval_QNAME, Integer.class, null, value);
    }

}
